mq:
  host: localhost
  port: 61616
  user: artemis
  password: artemis
jobs:
  transcodingQueue: jms/transcoderQueue
  managementQueue: jms/managementQueue
aws:
  baseUrl: http://localhost:9000
  region: ap-south-1
  buckets:
    rawVideos: raw-videos
    transcodedVideos: transcoded-videos