apiVersion: v1
kind: ConfigMap
metadata:
  name: config-chart
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  config.yml: |
    mq:
      host: localhost
      port: 61616
      user: artemis
      password: artemis
    jobs:
      transcodingQueue: jms/transcoderQueue
      managementQueue: jms/managementQueue
    aws:
      baseUrl: http://localhost:9000
      region: ap-south-1
      buckets:
        rawVideos: raw-videos
        transcodedVideos: transcoded-videos
    db:
      url: localhost:5432
      username: postgres
      password: pass
  