apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  config.yml: |
    mq:
      host: artemis-service.artemis-dev.svc.cluster.local
      port: 61616
      user: artemis
      password: artemis
    jobs:
      transcodingQueue: jms/transcoderQueue
      managementQueue: jms/managementQueue
    aws:
      baseUrl: http://minio-service.minio-dev.svc.cluster.local:9000
      region: ap-south-1
      buckets:
        rawVideos: raw-videos
        transcodedVideos: transcoded-videos
    db:
      url: postgres-postgresql.postgres.svc.cluster.local:5432
      username: service_user
      password: test_service_user
    auth:
      url: http://keycloak.keycloak.svc.cluster.local:8080/realms/yt-clone
