CREATE TABLE IF NOT EXISTS FILE_STATUS (
    id BIGINT PRIMARY KEY,
    vid BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    message TEXT,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    MODIFIED_AT TIMESTAMP DEFAULT NOW()
);

CREATE SEQUENCE IF NOT EXISTS FILE_STATUS_SEQ CACHE 20;